/* ══════════════════════════════════════════════════════════════════
   CafeDND / Tavern Table — Roadmap Data
   Two-Track Strategy:
     Track 1 — Research Version (Three.js + Tauri/Rust) — CLOSED
     Track 2 — Production Version (Godot 4.x) — PUBLIC (post-feedback gate)
══════════════════════════════════════════════════════════════════ */

const RESEARCH_PHASES = [
  {
    id: 'R0',
    track: 'RESEARCH',
    icon: '⚙️',
    color: '#00bcd4',
    title: 'Architecture & Setup',
    subtitle: 'Vite · Three.js · Tauri · Supabase',
    timeline: 'Weeks 1–2',
    snippet: 'Scaffold the full web + desktop stack. Nothing moves until the foundation is solid.',
    goal: 'Establish the complete development environment for both the browser version and the Tauri desktop wrapper. Every team member should be able to run the app locally by the end of this phase. No feature work happens here — only architecture decisions that are painful to change later.',
    tasks: [
      'Vite + TypeScript project scaffold with strict ESLint + Prettier',
      'Three.js r168+ installed and confirmed rendering a basic scene',
      'Tauri 2.0 initialized — Rust toolchain, Tauri CLI, wrapping the Vite app',
      'Supabase project created — auth (invite-only magic links), real-time, storage buckets',
      'Node.js + Socket.io server scaffolded for multiplayer state sync',
      'Canonical folder structure: src/scenes, src/systems, src/ui, src/networking, src/assets',
      'Git LFS configured for 3D model assets (.glb, .gltf, .hdr)',
      'CI pipeline (GitHub Actions) — lint, type-check, build on every push',
      'Dev environment setup guide written for all team members',
    ],
    deliverable: 'Every team member runs `npm run dev` and sees a Three.js canvas. Tauri builds a native window from the same code. Supabase auth works with an invite link.',
    gate: 'Can the whole team build and run the app locally in under 10 minutes from the README?',
  },
  {
    id: 'R1',
    track: 'RESEARCH',
    icon: '🏠',
    color: '#26c6da',
    title: '3D Room & Core Scene',
    subtitle: 'The Basement · Camera · Lighting',
    timeline: 'Weeks 2–4',
    snippet: 'A warm, atmospheric room that makes you want to sit down and play.',
    goal: 'Build the core 3D environment in Three.js. Players need to feel like they\'re somewhere real — the room must establish atmosphere before any game systems exist. This is the emotional foundation the entire product sits on.',
    tasks: [
      'Three.js WebGLRenderer with PBR materials (MeshStandardMaterial throughout)',
      '"The Basement" room geometry — floor, walls, ceiling, wood paneling via GLTF or BoxGeometry',
      'Central table as a separate mesh with its own material (required for SubViewport later)',
      'Chairs placed at seated positions around the table — each chair has a defined seat transform',
      'Warm lighting: OmniLight equivalents (PointLight), soft DirectionalLight for fill',
      'Atmospheric FogExp2 + ambient occlusion baked into textures',
      'Seated camera system — OrbitControls constrained to head-height, limited yaw/pitch',
      'GLTF asset pipeline: GLTFLoader + Draco compression + KTX2 textures',
      'Stats.js overlay in dev mode — must hold 60fps on GTX 1060 equivalent',
    ],
    deliverable: 'A 3D basement room that runs at 60fps. You sit at the table, look around, and it feels like a place. No game logic yet — just the environment.',
    gate: 'Does the room immediately communicate "D&D basement" without any explanation?',
  },
  {
    id: 'R2',
    track: 'RESEARCH',
    icon: '🔮',
    color: '#4caf50',
    title: 'Peek Mechanic & Map System',
    subtitle: 'Render-to-Texture · Map Grid · Fog of War',
    timeline: 'Weeks 4–7',
    snippet: 'The signature feature: dive through the table into the world below.',
    goal: 'Implement the Peek mechanic — the product\'s defining experience. The table surface renders a live 2D map via WebGLRenderTarget. Pressing Peek smoothly transitions the camera through the table plane into a full 3D world. This phase proves the technical thesis.',
    tasks: [
      'WebGLRenderTarget for table surface — second Three.js scene rendered as a texture onto the table mesh',
      'World map scene: separate scene graph with terrain tiles, props, and tokens',
      'Smooth Peek transition: GSAP timeline animating camera position + rotation through the table plane',
      'Grid-based tile map data structure — tile types (terrain), occupants (tokens), revealed state (fog)',
      'Terrain tile renderer — grass, stone, water, sand, lava tile materials',
      'Token objects: 3D cylinders with portrait textures, draggable for DM',
      'Fog of war: custom fragment shader masking unrevealed tiles with dark mist',
      'Peek-to-table return animation (reverse transition)',
      'Network sync preparation: map state serialization (tile grid, token positions, fog mask)',
    ],
    deliverable: 'The Peek mechanic works end-to-end: table shows a map, press Peek, camera dives through, you\'re in the 3D world. Fog of war hides unrevealed tiles. DM can place and move tokens.',
    gate: 'Does Peek feel magical? Does watching the camera dive through the table make someone say "whoa"?',
  },
  {
    id: 'R3',
    track: 'RESEARCH',
    icon: '🌐',
    color: '#ff9800',
    title: 'Multiplayer & Session Architecture',
    subtitle: 'Socket.io · Lobby · Role Auth · Tauri IPC',
    timeline: 'Weeks 7–10',
    snippet: 'Real-time multiplayer with DM authority. Two people in the same session.',
    goal: 'Two clients connect to the same session and see the same world state. DM has authority over the map, fog, and tokens. Players can only interact within their permitted scope. This is the hardest technical phase — network architecture mistakes are expensive to fix later.',
    tasks: [
      'Socket.io server: room management, DM/player role assignment, broadcast events',
      'Lobby system: DM creates session → receives a 6-char room code, players join by code',
      'Role-based permission enforcement: DM commands (map edit, fog, all tokens) vs Player commands (own token only)',
      'State sync events: tokenMoved, fogRevealed, mapTileChanged, diceRolled — all server-validated',
      'Player registry: seat index, display name, role, connected/disconnected state',
      'Reconnection handling: socket.io auto-reconnect + server state recovery on rejoin',
      'Supabase persistence: campaign data saved on DM actions, session restored on reconnect',
      'Tauri IPC bridge: Rust commands for local file save/load (campaign JSON to disk)',
      'Multi-window/tab support: DM and player can open separate browser windows for split-screen',
      'Invite-only auth: Supabase magic links so only invited users can join sessions',
    ],
    deliverable: 'DM and player join the same session via room code. DM moves a token — player sees it move. DM reveals fog — player sees the map expand. Disconnecting and rejoining restores state.',
    gate: 'Is the state sync reliable under normal network conditions? Does reconnect work without losing session state?',
  },
  {
    id: 'R4',
    track: 'RESEARCH',
    icon: '⚔️',
    color: '#ef5350',
    title: 'Core Game Systems',
    subtitle: 'Physics Dice · Character Sheet · Combat Loop',
    timeline: 'Weeks 10–13',
    snippet: 'Physics dice that feel real, character sheets, and a working combat turn loop.',
    goal: 'Implement the mechanical core of D&D 5e: dice that roll with physics, a character sheet that tracks stats and HP, and an initiative-based combat turn loop. These are the systems that separate a "cool demo" from a tool people can actually play with.',
    tasks: [
      'Rapier.js (WASM) physics world for dice — rigid bodies, collision meshes, friction/restitution tuning',
      '3D dice models: d4, d6, d8, d10, d12, d20 with Rapier convex hull colliders',
      'Throw animation: random impulse + angular velocity applied on roll click',
      'Face-up detection: raycast or face normal comparison after physics settles',
      'Roll result broadcast to all session clients with roller identity',
      'TypeScript data model for 5e character sheet (stats, modifiers, skills, HP, features, spell slots)',
      'Character sheet UI panel: all stats visible, HP editable, conditions toggleable',
      'Initiative tracker: auto-roll (d20 + DEX mod), drag-to-reorder, synced current-turn highlight',
      'HP sync: DM applies damage/healing → all clients see HP bars update live',
      'Turn management: current turn broadcast, action/bonus/reaction state per turn',
    ],
    deliverable: 'Roll a d20 — it tumbles with physics and the result appears for everyone. Open the character sheet — HP, stats, and skills are all there. Run initiative — the tracker shows whose turn it is.',
    gate: 'Do the dice feel satisfying enough that players roll them for fun, not just to get a number?',
  },
  {
    id: 'R5',
    track: 'RESEARCH',
    icon: '🎛️',
    color: '#9c27b0',
    title: 'DM & Player Interfaces',
    subtitle: 'DM Screen · Player Screen · Chat · Audio',
    timeline: 'Weeks 13–16',
    snippet: 'DM gets a command center. Players get a clean, immersive view.',
    goal: 'Build the two split interfaces that define the product\'s UX: the DM\'s command center and the player\'s immersive table view. The DM screen must feel powerful but not overwhelming. The player screen must feel like sitting at a table, not operating a dashboard.',
    tasks: [
      'DM screen layout: left sidebar (tools), center 3D viewport, right panel (initiative, party status)',
      'Map editor panel: tile palette, fog brush, prop placement, token library',
      'Encounter panel: enemy list with HP, conditions, drag-to-initiative-order',
      'DM notes panel: plain-text scratchpad, auto-saves to Supabase every 30s',
      'Player screen layout: full 3D table view, bottom bar (Character, Dice, Chat tabs)',
      'Character sheet tab: full 5e sheet, editable HP, class feature tracking',
      'Dice tab: all dice with quick-roll presets, roll history',
      'Text chat: in-character and OOC channels, whisper-to-player, whisper-to-DM',
      'Ambient audio engine: Howler.js with DM-controlled looping tracks (Basement, Tavern, Combat, etc.)',
      'Basic NPC manager: name/portrait/stats card, DM can display dialogue to all players',
    ],
    deliverable: 'DM can run a session from this interface without needing another tool open. Players have everything they need in the bottom bar. Chat, dice, and audio all work together.',
    gate: 'Can a DM who has never used the app run a 30-minute session after a 5-minute introduction?',
  },
  {
    id: 'R6',
    track: 'RESEARCH',
    icon: '✨',
    color: '#8bc34a',
    title: 'Internal Polish & QA',
    subtitle: 'Team Playtesting · Tauri Packaging · Performance',
    timeline: 'Weeks 16–18',
    snippet: 'Tighten everything before outside eyes see it. Package for desktop.',
    goal: 'Bring the app to internal release quality: consistent UI, solid performance, packaged as a native app via Tauri, and tested by the team in real play sessions. Find the rough edges before external playtesters encounter them.',
    tasks: [
      'UI consistency pass — fonts, spacing, colors, and hover states unified across both screens',
      'Performance audit: draw call batching, texture compression (KTX2), targeted 60fps on integrated graphics',
      'Tauri native packaging: Windows (.msi), macOS (.dmg), Linux (.AppImage) — all auto-signed',
      'Error handling UX: network disconnect banner, graceful reconnect, corrupted state recovery',
      'Loading states and skeleton screens for all async operations',
      'Keyboard shortcut documentation + in-app shortcut overlay (press ?)',
      'Internal team play sessions: minimum 2 full sessions of 1.5+ hours each',
      'Bug tracking in GitHub Issues — all critical bugs fixed before external beta',
      'Internal feedback questionnaire (UX pain points, feature gaps, "what was confusing")',
      'Session recording infrastructure: OBS profile or built-in screen-share for observation sessions',
    ],
    deliverable: 'The research version is stable, packaged, and has survived 2+ full play sessions internally. No critical bugs. Team is confident to show it to outsiders.',
    gate: 'Would every team member confidently show this to an external playtester without embarrassment?',
  },
  {
    id: 'R7',
    track: 'RESEARCH',
    icon: '📋',
    color: '#ffc107',
    title: 'Closed Playtesting & Feedback Gate',
    subtitle: 'External Beta · Metrics · Go / No-Go Decision',
    timeline: 'Weeks 18–24',
    snippet: 'Real D&D groups. Real feedback. The gate that unlocks the Godot production track.',
    goal: 'Put the research version in front of 8–15 invited D&D groups and gather the structured data needed to make a confident go/no-go decision on the Godot production track. This is not just QA — it\'s strategic validation of the entire CafeDND concept.',
    tasks: [
      'Recruit 8–15 external D&D groups (mix of regular players, VTT veterans, and newcomers)',
      'Tester onboarding guide: install Tauri app OR use browser link, account setup, first session walkthrough',
      'Facilitated observation sessions: screen-share or in-person, 1 team member observing per session',
      'Post-session questionnaire: 15 questions covering UX, Peek mechanic, atmosphere, vs current tool',
      'Metric tracking: session length, features used, error events, drop-off points (Supabase analytics)',
      'Weekly synthesis: debrief meetings to identify patterns across tester groups',
      'Critical bug fixes during beta period (P0 bugs fixed within 48h)',
      'Compile final feedback report: quantitative metrics + qualitative themes + recommendation',
      'Go/No-Go decision meeting with stakeholders — minimum threshold: 70% of groups prefer over current VTT',
      'If GO: author "Godot Architecture Learnings" document carrying UX insights into production build',
    ],
    deliverable: 'Written feedback report with go/no-go recommendation. If green: Godot production track is unlocked and informed by 6 months of real-world usage data.',
    gate: 'Do 70%+ of playtesting groups say they would use CafeDND for their actual campaigns over their current tool?',
  },
];

const GODOT_PHASES = [
  {
    id: 'G0',
    track: 'GODOT',
    icon: '🏗️',
    color: '#ff9800',
    title: 'Godot Foundation',
    subtitle: 'Informed by Research Version learnings',
    timeline: 'Months 1–2 (post-gate)',
    snippet: 'Godot setup, networking proven, first two players in the same room.',
    goal: 'Port the proven UX insights from the Research Version into Godot\'s architecture. Every networking and scene-structure decision is now informed by 6 months of real-world usage. Get two clients into the same 3D room with networked avatars.',
    tasks: [
      'Godot 4.4+ project setup — folder structure, Git LFS, coding standards, GDScript style guide',
      'Autoload singletons: GameManager, NetworkManager, AudioManager, UIManager',
      '3D room environment — port "The Basement" to Godot with Forward+ renderer (Vulkan)',
      'ENet networking with Godot MultiplayerAPI — host/join lobby, two clients in same room',
      'Seated camera controller — third-person, clamped mouse-look, seat assignment system',
      'Placeholder avatars — simple humanoid, synced across clients via MultiplayerSynchronizer',
      'UI shell — DM screen + player screen placeholder panels (non-functional)',
      'Carry forward research findings: document what UX patterns proved most valuable',
    ],
    deliverable: 'Two players join a Godot room via lobby and see each other\'s avatars at the table. The room already benefits from the visual polish lessons learned in the research phase.',
    gate: 'Is the Godot networking more stable than the Socket.io research version? What did we improve?',
  },
  {
    id: 'G1',
    track: 'GODOT',
    icon: '🔮',
    color: '#4caf50',
    title: 'Table Comes Alive',
    subtitle: 'SubViewport · Map Editor · Peek v1 · Dice',
    timeline: 'Months 3–5',
    snippet: 'Map on the table, Peek into a 3D world, tokens move, physics dice roll.',
    goal: 'Re-implement the core VTT loop in Godot\'s rendering pipeline. The Peek mechanic gets its full Godot treatment with Vulkan rendering, SubViewport, and proper LOD. This is the research version\'s R2 but with better performance and visual fidelity.',
    tasks: [
      'SubViewport table surface — render world map scene from overhead orthographic camera',
      'Tile-based map editor for DM — drag terrain tiles, place props, save/load maps',
      'Fog of war system — shader-based masking, DM paints reveals, synced to all clients',
      'Peek mechanic v1 — Tween camera through table plane into world scene (Godot scene transition)',
      'Token system — MultiplayerSpawner for tokens, DM places all, players move their own',
      '3D physics dice with Jolt Physics — d4 through d20, networked roll results',
      'Full state sync via MultiplayerSynchronizer — map, tokens, fog, dice',
    ],
    deliverable: 'Functional VTT in Godot. DM builds a map, players Peek, tokens move, dice roll — all synced. Better visual quality than the research version.',
    gate: 'Is the Peek mechanic noticeably better in Godot vs the Three.js research version?',
  },
  {
    id: 'G2',
    track: 'GODOT',
    icon: '👥',
    color: '#2196f3',
    title: 'Avatar & Social Layer',
    subtitle: 'Character Creator · Emotes · Voice · Chat',
    timeline: 'Months 6–7',
    snippet: 'Expressive avatars, voice chat, the table feels like hanging out with friends.',
    goal: 'This is what separates Tavern Table from every browser VTT. Customizable 3D avatars sitting around the table, expressing reactions, talking to each other. Social immersion must be established before the game mechanics are layered on top.',
    tasks: [
      'Avatar creator — race, body, skin, hair, face, accessories with real-time preview',
      'Idle animation system — fidgeting, leaning, table-tapping, looking around',
      'Emote system — cheer, facepalm, thinking, laughing, scared (triggered by emote wheel)',
      'Emote wheel UI — radial menu on keybind, visible to all players',
      'WebRTC voice chat via GDExtension or Discord integration',
      'Text chat — in-character / OOC channels, whisper, party chat',
      'Persistent player profiles — avatar saved across campaigns',
    ],
    deliverable: 'Players look unique. Avatars react in real time. Voice and chat work. The table is socially alive even before any game content loads.',
    gate: 'Do players spend time personalizing their avatar? Do they use emotes unprompted?',
  },
  {
    id: 'G3',
    track: 'GODOT',
    icon: '⚔️',
    color: '#f44336',
    title: 'Character & Combat',
    subtitle: 'Full 5e · Initiative · Combat Loop',
    timeline: 'Months 8–10',
    snippet: 'Full 5e character sheets and a complete combat encounter from initiative to resolution.',
    goal: 'Players have complete 5e character sheets. Combat runs end-to-end without any paper. Every mechanic from the research version\'s R4 is reproduced here with Godot\'s UI framework — more polished, more integrated.',
    tasks: [
      'Full 5e character sheet — stats, skills, HP, class features, spell slots, death saves',
      'Character creation wizard — step-by-step (race, class, scores, background, equipment)',
      'Initiative tracker — auto-roll, drag-to-reorder, synced turn indicator',
      'Combat flow — action/bonus/reaction, grid movement with range display',
      'Encounter builder — SRD bestiary, drag enemies to init, CR vs party calculator',
      'Condition system — poisoned, stunned, prone, etc. — synced to all, shown on tokens',
      'Death saves UI — automated tracking with stabilization logic',
      'Combat log — scrollable timestamped history',
    ],
    deliverable: 'A real D&D group runs a complete combat encounter in Godot. Initiative to final blow — no paper, no alt-tab.',
    gate: 'Can a group of 4-5 players complete a combat session without hitting a blocking bug?',
  },
  {
    id: 'G4',
    track: 'GODOT',
    icon: '🧩',
    color: '#9c27b0',
    title: 'Puzzles & DM Power Tools',
    subtitle: 'Puzzle Engine · NPCs · Loot · Music · Rules',
    timeline: 'Months 11–13',
    snippet: 'Complete DM toolkit — puzzles, NPCs, loot, ambiance, and a rules reference.',
    goal: 'The DM can run any type of session — combat, exploration, social, puzzle — entirely within Tavern Table. No alt-tabbing to Notion, Spotify, or Discord.',
    tasks: [
      'Puzzle framework + quick templates (riddle, sliding tile, combo lock, Simon, word cipher)',
      'Multi-layer puzzle builder — chain puzzles, conditional hints, in-game triggers',
      'Puzzle viewport — renders on table, all players interact simultaneously',
      'NPC manager — portrait cards, quick dialogue display, relationship tracker',
      'Loot table system — weighted random generation, drag to player inventories',
      'Rules reference — searchable SRD database, bookmarks, homebrew entries',
      'DM notes — rich text, auto-save, tags, session log linking',
      'Music & ambiance controller — playlists, crossfade, SFX board (synced to players)',
    ],
    deliverable: 'DM runs a full non-combat session using only Tavern Table. Puzzles work. NPCs have dialogue. Music plays.',
    gate: 'Could a DM replace their entire current session toolkit (Notion + Spotify + Discord) with this app alone?',
  },
  {
    id: 'G5',
    track: 'GODOT',
    icon: '🌍',
    color: '#8bc34a',
    title: 'World Building & Peek 2.0',
    subtitle: 'Heightmap Terrain · 3D Props · Volumetric Fog',
    timeline: 'Months 14–16',
    snippet: 'The 3D world under the table becomes rich, beautiful, and a genuine wow moment.',
    goal: 'Peek 2.0 justifies the full Godot investment. Heightmap terrain, real 3D props, dynamic weather, and volumetric fog of war — the world beneath the table is something no browser-based VTT can match.',
    tasks: [
      'Heightmap terrain system — paint elevations, blend textures, define biomes',
      '3D prop library — trees, buildings, ruins, rivers, fences, bridges, dungeons',
      'Dynamic lighting — DM-controlled time-of-day and weather (rain, fog, snow)',
      'Peek 2.0 — smooth fly-through, point-of-interest focus, animated transition',
      'Volumetric fog of war — unexplored areas shrouded in VoxelGI-based mist',
      'Map import pipeline — images, Dungeondraft, Inkarnate exports as references',
      'Player Peek tools — personal pins, party-shared markers, distance measure',
    ],
    deliverable: 'Peeking is a "screenshot moment." Vulkan rendering makes the world look better than any existing VTT. Players share clips.',
    gate: 'Would a player spontaneously record and share a Peek clip without being asked?',
  },
  {
    id: 'G6',
    track: 'GODOT',
    icon: '🚀',
    color: '#ffc107',
    title: 'Polish, Platform & Launch',
    subtitle: 'Beta · Steam Early Access · Performance',
    timeline: 'Months 17–19',
    snippet: 'Production quality. Real groups choose it over Roll20. Ship to Early Access.',
    goal: 'Every system reaches production quality. A closed beta with real D&D groups proves the product is ready. Early Access launches on Steam and itch.io.',
    tasks: [
      'Multiple room environments: Basement, Tavern Backroom, Scholar\'s Study, Restaurant Booth',
      'DM environment customization — props, lighting, ambient audio per room',
      'UI/UX polish — transitions, tooltips, empty states, onboarding tutorial',
      'Performance optimization — LOD, occlusion culling, GPU profiling, network tick tuning',
      'Cloud save & sync via Supabase — campaign backup, cross-device access',
      'Accessibility — colorblind modes, scalable UI, full key remapping',
      'Closed beta with 10+ real D&D groups — structured feedback cycles',
      'Platform builds: Windows, macOS, Linux + web export evaluation',
      'Steam page, itch.io listing, trailer, press kit, marketing materials',
    ],
    deliverable: 'Early Access live. Beta groups choose Tavern Table for their actual campaigns.',
    gate: 'Do 70%+ of beta testers say they\'d use Tavern Table for their next campaign?',
  },
  {
    id: 'G7',
    track: 'GODOT',
    icon: '🌟',
    color: '#ff5722',
    title: 'Post-Launch & Expansion',
    subtitle: 'Mobile · Modding · Marketplace · VR · AI',
    timeline: 'Month 20+',
    snippet: 'Mobile companion, modding support, campaign marketplace, VR Peek, and AI DM tools.',
    goal: 'Grow Tavern Table into a community-driven D&D ecosystem. The best content — campaigns, maps, monsters, rooms — should come from the community, not just the dev team.',
    tasks: [
      'Mobile companion app — character sheet, dice, Peek for phones and tablets',
      'Modding API — custom environments, puzzle types, tokens, monster packs',
      'Campaign marketplace — community-created content with revenue share',
      'VR mode — physically lean over the table to Peek (Peek mechanic built for this)',
      'Additional rulesets — Pathfinder 2e, OSR systems, custom homebrew engines',
      'AI DM tools — NPC dialogue generation, encounter suggestions (Claude API integration)',
      'Spectator mode — watch live campaigns as a non-participant',
      'Session replay and streaming tools for content creators',
    ],
    deliverable: 'Active platform. Community creates content the dev team could not have built alone.',
    gate: 'Is the community generating campaigns, mods, and maps without being asked?',
  },
];

const ALT_PATHS = [
  {
    color: '#4caf50',
    badge: 'Path A',
    title: 'Minimal',
    timeline: '6–8 months to a playable research VTT',
    desc: 'Strip the research version to the bare loop: join → sit → see map → roll dice → run combat. No Peek, no avatars, no puzzles. Fastest validation path.',
    items: [
      '2D map on table surface only — no Peek mechanic',
      'Fixed placeholder avatars, combat-only session flow',
      'Single static room, invite-only browser access',
      'No Tauri packaging — browser only for research',
    ],
    tradeoff: 'No differentiator. If feedback is mediocre you won\'t know whether the concept or the scope is the problem.',
    rec: false,
  },
  {
    color: '#c9a227',
    badge: 'Path B',
    title: 'Balanced',
    timeline: '~6 months research + ~19 months Godot',
    desc: 'Full research version with all 8 phases, then Godot production after the gate. The recommended path — research informs production, reducing total risk.',
    items: [
      'Full Three.js + Tauri research version (R0–R7)',
      'Proper feedback gate before Godot commitment',
      'Peek mechanic validated before production investment',
      'Avatar system in production pulled forward (G2)',
      'Steam Early Access as the public commercial product',
    ],
    tradeoff: 'Longer total timeline (~25 months end-to-end). Justified by dramatically lower risk on the Godot production investment.',
    rec: true,
  },
  {
    color: '#9c27b0',
    badge: 'Path C',
    title: 'Comprehensive',
    timeline: 'Research + 18–24 months Godot',
    desc: 'Research version PLUS AI DM tools in v1 of production, web-first Godot export, and mobile companion at launch — built to displace Roll20 permanently.',
    items: [
      'Research version ships with Claude API AI DM tools',
      'Godot production: web export as primary target',
      'Mobile companion app at launch, not post-launch',
      'Foundry-style modding system from day one',
      'Discord Rich Presence + streaming/clip tools',
    ],
    tradeoff: 'Requires funding or 5+ person team. High scope risk. The version that could permanently end Roll20\'s dominance.',
    rec: false,
  },
];
