/* ══════════════════════════════════════════════════════════════════
   CafeD&D · TavernTable — Roadmap Data
   Strategy (2026-08-18 restructure):
     THE PRODUCT — TavernTable web build (Three.js + Vite + Socket.io) — DN-006
       Primary delivery: hosted website (browser, no install)
       Later: Tauri desktop wrapper (R8, after website is stable)
       Auth/DB: local mock (R0–R6) → Supabase (R7, closed testing only)
     CONTINGENCY — Godot rebuild (G0–G7), dormant; activates only on a blocking technical ceiling (DN-006)
══════════════════════════════════════════════════════════════════ */

const RESEARCH_PHASES = [
  {
    id: 'R0',
    track: 'RESEARCH',
    icon: '⚙️',
    color: '#00bcd4',
    title: 'Architecture & Setup',
    subtitle: 'Vite · Three.js · Socket.io · Local Server',
    timeline: 'Weeks 1–2',
    snippet: 'Scaffold the web stack and local server. Four dev lanes, typed contracts, running locally for everyone.',
    goal: 'Establish the complete local development environment. Every team member should be able to run both the Vite client and the Socket.io server locally by the end of this phase. No cloud dependencies yet — Supabase and Tauri are deferred. Focus: monorepo structure, shared type contracts, and the four developer lane boundaries that keep parallel work clean.',
    tasks: [
      'Vite + TypeScript project scaffold with strict ESLint + Prettier',
      'Three.js r168+ installed and confirmed rendering a basic scene in the browser',
      'Node.js + Socket.io server scaffolded — runs locally on port 3000, client connects on 5173',
      'Local mock auth: hardcoded session tokens, no email or cloud required for R0–R6',
      'Canonical folder structure established: src/scenes, src/systems, src/physics, src/ui, src/networking, src/audio, src/data, server/, shared/',
      'shared/types.ts created — all socket event names and payload types live here, imported by both client and server',
      'Four CLAUDE.md dev-lane instruction files placed: src/scenes/, src/systems/, server/, src/ui/',
      'Git + GitHub repo configured — .gitignore covers node_modules, dist, screenshots, *.pptx',
      'CI pipeline (GitHub Actions) — lint, type-check, build on every push',
      'Dev environment setup guide: `npm run dev` (client) + `npm run server:dev` (server) from README',
    ],
    deliverable: 'Every team member runs `npm run dev` (Vite at :5173) and `npm run server:dev` (Socket.io at :3000) and sees a Three.js canvas connected to the local server. No Supabase, no Tauri needed.',
    gate: 'Can any team member spin up the full local dev environment in under 10 minutes from the README?',
  },
  {
    id: 'R1',
    track: 'RESEARCH',
    icon: '🏠',
    color: '#26c6da',
    title: '3D Room & Core Scene',
    subtitle: 'The Basement · Camera · Lighting',
    timeline: 'Weeks 2–4',
    snippet: 'A warm, atmospheric room that makes you want to sit down and play.',
    goal: 'Build the core 3D environment in Three.js. Players need to feel like they\'re somewhere real — the room must establish atmosphere before any game systems exist. This is the emotional foundation the entire product sits on.',
    tasks: [
      'Three.js WebGLRenderer with PBR materials (MeshStandardMaterial throughout)',
      '"The Basement" room geometry — floor, walls, ceiling, wood paneling via GLTF or BoxGeometry',
      'Central table as a separate mesh with its own material (required for SubViewport later)',
      'Chairs placed at seated positions around the table — each chair has a defined seat transform',
      'Warm lighting: OmniLight equivalents (PointLight), soft DirectionalLight for fill',
      'Atmospheric FogExp2 + ambient occlusion baked into textures',
      'Seated camera system — OrbitControls constrained to head-height, limited yaw/pitch',
      'GLTF asset pipeline: GLTFLoader + Draco compression + KTX2 textures',
      'Stats.js overlay in dev mode — must hold 60fps on GTX 1060 equivalent',
    ],
    deliverable: 'A 3D basement room that runs at 60fps. You sit at the table, look around, and it feels like a place. No game logic yet — just the environment.',
    gate: 'Does the room immediately communicate "D&D basement" without any explanation?',
  },
  {
    id: 'R2',
    track: 'RESEARCH',
    icon: '🔮',
    color: '#4caf50',
    title: 'Peek Mechanic & Map System',
    subtitle: 'Render-to-Texture · Map Grid · Fog of War',
    timeline: 'Weeks 4–7',
    snippet: 'The signature feature: dive through the table into the world below.',
    goal: 'Implement the Peek mechanic — the product\'s defining experience. The table surface renders a live 2D map via WebGLRenderTarget. Pressing Peek smoothly transitions the camera through the table plane into a full 3D world. This phase proves the technical thesis.',
    tasks: [
      'WebGLRenderTarget for table surface — second Three.js scene rendered as a texture onto the table mesh',
      'World map scene: separate scene graph with terrain tiles, props, and tokens',
      'Smooth Peek transition: GSAP timeline animating camera position + rotation through the table plane',
      'Grid-based tile map data structure — tile types (terrain), occupants (tokens), revealed state (fog)',
      'Terrain tile renderer — grass, stone, water, sand, lava tile materials',
      'Token objects: 3D cylinders with portrait textures, draggable for DM',
      'Fog of war: custom fragment shader masking unrevealed tiles with dark mist',
      'Peek-to-table return animation (reverse transition)',
      'Network sync preparation: map state serialization (tile grid, token positions, fog mask)',
      '[PLACEHOLDER — see DN-003] PropDescriptor.modelUrl typed and stubbed; AssetLibrary scaffold created in src/assets/assetLibrary.ts — full GLB loading wired in R5.',
    ],
    deliverable: 'The Peek mechanic works end-to-end: table shows a map, press Peek, camera dives through, you\'re in the 3D world. Fog of war hides unrevealed tiles. DM can place and move tokens.',
    gate: 'Does Peek feel magical? Does watching the camera dive through the table make someone say "whoa"?',
  },
  {
    id: 'R3',
    track: 'RESEARCH',
    icon: '🌐',
    color: '#ff9800',
    title: 'Multiplayer & Session Sync',
    subtitle: 'Socket.io · Lobby · Role Auth · Local Server',
    timeline: 'Weeks 7–10',
    snippet: 'Real-time multiplayer with DM authority. Two browser tabs in the same session via local server.',
    goal: 'Two browser clients connect to the local Socket.io server and see the same world state. DM has authority over the map, fog, and tokens. Players can only interact within their permitted scope. All state lives in memory on the server — no cloud dependency. This is the hardest technical phase: network architecture mistakes are expensive to fix later.',
    tasks: [
      'Socket.io server: room management, DM/player role assignment, broadcast events — all in server/session.ts',
      'Lobby system: DM creates session → receives a 6-char room code, players join by code in browser',
      'Role-based permission enforcement: DM commands (map edit, fog, all tokens) vs Player commands (own token only)',
      'All socket event names reference shared/types.ts — no hardcoded strings in handlers',
      'State sync events: tokenMoved, fogRevealed, mapTileChanged, diceRolled — all server-validated',
      'Player registry: seat index, display name, role, connected/disconnected state (in-memory)',
      'Reconnection handling: socket.io auto-reconnect + server in-memory state recovery on rejoin',
      'Campaign persistence: local JSON files written by the server on DM actions (no Supabase yet)',
      'Multi-window/tab support: DM and player open separate browser windows at localhost:5173',
      'Mock auth: any { name, token } pair accepted by server — no email or invite flow yet',
    ],
    deliverable: 'DM and player join the same session via room code in two browser windows. DM moves a token — player sees it move. DM reveals fog — player sees the map expand. Disconnecting and rejoining restores state from server memory.',
    gate: 'Is the state sync reliable under normal network conditions? Does reconnect work without losing session state?',
  },
  {
    id: 'R4',
    track: 'RESEARCH',
    icon: '⚔️',
    color: '#ef5350',
    title: 'Core Game Systems',
    subtitle: 'Physics Dice · Character Sheet · Combat Loop',
    timeline: 'Weeks 10–13',
    snippet: 'Physics dice that feel real, character sheets, and a working combat turn loop.',
    goal: 'Implement the mechanical core of D&D 5e: dice that roll with physics, a character sheet that tracks stats and HP, and an initiative-based combat turn loop. These are the systems that separate a "cool demo" from a tool people can actually play with.',
    tasks: [
      'Rapier.js (WASM) physics world for dice — rigid bodies, collision meshes, friction/restitution tuning',
      '3D dice models: d4, d6, d8, d10, d12, d20 with Rapier convex hull colliders',
      'Throw animation: random impulse + angular velocity applied on roll click',
      'Face-up detection: raycast or face normal comparison after physics settles',
      'Roll result broadcast to all session clients with roller identity',
      'TypeScript data model for 5e character sheet (stats, modifiers, skills, HP, features, spell slots)',
      'Character sheet UI panel: all stats visible, HP editable, conditions toggleable',
      'Initiative tracker: auto-roll (d20 + DEX mod), drag-to-reorder, synced current-turn highlight',
      'HP sync: DM applies damage/healing → all clients see HP bars update live',
      'Turn management: current turn broadcast, action/bonus/reaction state per turn',
    ],
    deliverable: 'Roll a d20 — it tumbles with physics and the result appears for everyone. Open the character sheet — HP, stats, and skills are all there. Run initiative — the tracker shows whose turn it is.',
    gate: 'Do the dice feel satisfying enough that players roll them for fun, not just to get a number?',
  },
  {
    id: 'R5',
    track: 'RESEARCH',
    icon: '🎛️',
    color: '#9c27b0',
    title: 'DM & Player Interfaces',
    subtitle: 'DM Screen · Player Screen · Chat · Audio · Atmosphere',
    timeline: 'Weeks 13–16',
    snippet: 'DM gets a command center. Players get a clean, immersive view. DM controls the room\'s atmosphere.',
    goal: 'Build the two split interfaces that define the product\'s UX: the DM\'s command center and the player\'s immersive table view. The DM screen must feel powerful but not overwhelming. The player screen must feel like sitting at a table, not operating a dashboard. The DM also controls atmosphere — room choice and day/night lighting — so every session can feel distinct without any external tools.',
    tasks: [
      'DM screen layout: left sidebar (tools), center 3D viewport, right panel (initiative, party status)',
      'Map editor panel: tile palette, fog brush, prop placement, token library',
      'Encounter panel: enemy list with HP, conditions, drag-to-initiative-order',
      'DM notes panel: plain-text scratchpad, auto-saves to local JSON every 30s',
      'Player screen layout: full 3D table view, bottom bar (Character, Dice, Chat tabs)',
      'Character sheet tab: full 5e sheet, editable HP, class feature tracking',
      'Dice tab: all dice with quick-roll presets, roll history',
      'Text chat: in-character and OOC channels, whisper-to-player, whisper-to-DM',
      'Ambient audio engine: Howler.js with DM-controlled looping tracks (Basement, Tavern, Combat, etc.)',
      'Basic NPC manager: name/portrait/stats card, DM can display dialogue to all players',
      '[DESIGN NOTE] Tavern room variant — second selectable room (warm pub interior: stone walls, fireplace, wooden beams). DM picks room before starting session in the lobby. Shares all game systems with The Basement; only the geometry, materials, and prop layout differ.',
      '[DESIGN NOTE] Day/Night atmosphere switch — DM toggles Day or Night lighting preset for the active room. Night: warm candlelit (current Basement default). Day: cooler ambient fill, brighter window-light directional, reduced candle intensity. 3-second smooth lerp on all light intensities and fog density, broadcast to all players simultaneously.',
      '[DESIGN NOTE] Dynamic theme & asset library (DN-003) — DM prop picker queries AssetLibrary.listByKind() for the active theme. Selecting a GLB model sets PropDescriptor.modelUrl. WorldScene.addProp() and RoomScene miniatures check modelUrl and load via AssetLibrary, falling back to procedural geometry. DM can also select a pre-built map layout (kind: "map") replacing the default tile grid. Asset kinds: prop, character, map, room. All GLBs live in /public/assets/ with Draco compression.',
    ],
    deliverable: 'DM can run a session from this interface without needing another tool open. Players have everything they need in the bottom bar. Chat, dice, audio, room choice, and day/night all work together.',
    gate: 'Can a DM who has never used the app run a 30-minute session after a 5-minute introduction?',
  },
  {
    id: 'R6',
    track: 'RESEARCH',
    icon: '✨',
    color: '#8bc34a',
    title: 'Website Launch & QA',
    subtitle: 'Hosted URL · Internal Dogfood · Performance',
    timeline: 'Weeks 16–19',
    snippet: 'Deploy the website. Internal team plays on the live URL. Zero critical bugs before outsiders see it.',
    goal: 'The research version goes from running only on localhost to running on a real hosted URL accessible to anyone with the link. The tavern-relay service is deployed alongside it; the game host itself stays wherever the DM runs it (own machine, a LAN machine, or a rented server) per the R4a DM-as-host model. The team plays real sessions on the live site and finds all remaining issues before external testers arrive.',
    tasks: [
      'UI consistency pass — fonts, spacing, colors, and hover states unified across both screens',
      'Performance audit: draw call batching, texture compression (KTX2), targeted 60fps on integrated graphics',
      'Vite client deployed to Vercel or Netlify — generates a shareable HTTPS URL',
      'tavern-relay deployed to Railway, Render, or VPS with TLS (wss://) — internet players reach the DM\'s host through it; the game host itself is NOT cloud-deployed (R4a DM-as-host)',
      'All three host placements verified from the live site: DM\'s own machine (via relay), a second machine on the DM\'s LAN (host-address field), and a DM-rented server',
      'Mixed-content check: the HTTPS site cannot open plain ws:// to non-localhost hosts — LAN/rented-server hosts need the relay path or TLS of their own; document the supported patterns',
      'CORS, WebSocket, and HTTPS configuration verified in production environment',
      'Error handling UX: network disconnect banner, graceful reconnect, corrupted state recovery',
      'Loading states and skeleton screens for all async operations',
      'Keyboard shortcut documentation + in-app shortcut overlay (press ?)',
      'Internal team play sessions on the live URL: minimum 2 full sessions of 1.5+ hours each',
      'Bug tracking in GitHub Issues — all critical bugs fixed before external beta',
      'Internal feedback questionnaire (UX pain points, feature gaps, "what was confusing")',
      'Session recording infrastructure: OBS or browser-based screen-share for observation sessions',
    ],
    deliverable: 'Website live at a real HTTPS URL. Team has played 2+ full sessions on it. Zero critical bugs. Ready for outsiders.',
    gate: 'Would every team member confidently share the link with an external playtester without embarrassment?',
  },
  {
    id: 'R7',
    track: 'RESEARCH',
    icon: '📋',
    color: '#ffc107',
    title: 'Supabase + Closed Playtesting',
    subtitle: 'Invite Auth · External Beta · Feedback Gate',
    timeline: 'Weeks 19–24',
    snippet: 'Real D&D groups, invite-only auth, Supabase wired in. The gate that unlocks the Godot track.',
    goal: 'Wire in Supabase for invite-only magic-link auth and session persistence, then put the app in front of 10–15 external D&D groups. Gather the structured data needed to make a confident go/no-go decision on the Godot production track. This is not just QA — it\'s strategic validation of the entire CafeDND concept.',
    tasks: [
      'Supabase project created — magic link auth, session persistence, storage buckets',
      'Auth adapter in server/auth.ts swapped from local mock to Supabase (adapter pattern means one file changes)',
      'Invite-only access: Supabase allowlist of tester email addresses — no public signup',
      'Campaign data migrated from local JSON to Supabase — session restore on reconnect from cloud',
      'Supabase analytics events wired for metric tracking (session length, features used, error events)',
      'Recruit 10–15 external D&D groups (mix: VTT veterans, newcomers, regular table players)',
      'Tester onboarding guide: open the website link, magic-link login, first session walkthrough',
      'Facilitated observation sessions: screen-share, 1 team member observing per group',
      'Post-session questionnaire: 15 questions covering UX, Peek mechanic, atmosphere, vs current tool',
      'Weekly synthesis: debrief meetings to identify patterns across tester groups',
      'P0 bug fixes within 48h during beta period',
      'Final feedback report: quantitative metrics + qualitative themes + go/no-go recommendation',
      'Go/No-Go decision meeting — minimum threshold: 70%+ of groups prefer CafeDND over current VTT',
      'If GO: author "Godot Architecture Learnings" document carrying UX insights into production build',
    ],
    deliverable: 'Written feedback report with go/no-go recommendation. If green: Godot production track unlocked, informed by months of real-world usage data.',
    gate: 'Do 70%+ of playtesting groups say they would use CafeDND for their actual campaigns over their current tool?',
  },
  {
    id: 'R8',
    track: 'RESEARCH',
    icon: '🖥️',
    color: '#78909c',
    title: 'Tauri Desktop Build',
    subtitle: 'Native App · Local File I/O · Optional Download',
    timeline: 'Post-R7 or parallel (R7+)',
    snippet: 'The website wrapped as a native desktop app. Optional for testers who prefer a download.',
    goal: 'Wrap the same website codebase in Tauri 2.0 to produce a native desktop application. This is not a separate product — it is the same Vite client in a native window, with a Rust IPC layer added for local file I/O. Tauri provides an optional download path for testers who prefer a native experience, and lays the groundwork for offline campaign saves.',
    tasks: [
      'Tauri 2.0 initialized in src-tauri/ — Rust toolchain, Tauri CLI, config files',
      'Vite client confirmed loading inside Tauri window without changes to web code',
      'Rust IPC commands: save_campaign(path, json) and load_campaign(path) for local file I/O',
      'tauri:fs capability added — scoped to campaign data directories only',
      'Tauri builds for Windows (.msi), macOS (.dmg), Linux (.AppImage)',
      'Code-signing setup: Windows Authenticode cert, macOS Developer ID + notarization',
      'Tauri update mechanism configured (optional auto-update via tauri-plugin-updater)',
      'GitHub Release workflow: tag → CI builds all three platform binaries → attaches to release',
      'Tester onboarding updated: "use the website OR download the desktop app" option',
      'Smoke test: all R7 features work identically in Tauri vs browser',
    ],
    deliverable: 'Signed native desktop builds for Windows, macOS, and Linux. Testers can choose website or download. Local campaign file I/O works in the Tauri version.',
    gate: 'Does the Tauri app work identically to the website for all playtesting scenarios? Does the local save/load add meaningful value?',
  },
];

const GODOT_PHASES = [
  {
    id: 'G0',
    track: 'GODOT',
    icon: '🏗️',
    color: '#ff9800',
    title: 'Godot Foundation',
    subtitle: 'Informed by Research Version learnings',
    timeline: 'Months 1–2 (post-gate)',
    snippet: 'Godot setup, networking proven, first two players in the same room.',
    goal: 'Port the proven UX insights from the Research Version into Godot\'s architecture. Every networking and scene-structure decision is now informed by 6 months of real-world usage. Get two clients into the same 3D room with networked avatars.',
    tasks: [
      'Godot 4.4+ project setup — folder structure, Git LFS, coding standards, GDScript style guide',
      'Autoload singletons: GameManager, NetworkManager, AudioManager, UIManager',
      '3D room environment — port "The Basement" to Godot with Forward+ renderer (Vulkan)',
      'ENet networking with Godot MultiplayerAPI — host/join lobby, two clients in same room',
      'Seated camera controller — third-person, clamped mouse-look, seat assignment system',
      'Placeholder avatars — simple humanoid, synced across clients via MultiplayerSynchronizer',
      'UI shell — DM screen + player screen placeholder panels (non-functional)',
      'Carry forward research findings: document what UX patterns proved most valuable',
    ],
    deliverable: 'Two players join a Godot room via lobby and see each other\'s avatars at the table. The room already benefits from the visual polish lessons learned in the research phase.',
    gate: 'Is the Godot networking more stable than the Socket.io research version? What did we improve?',
  },
  {
    id: 'G1',
    track: 'GODOT',
    icon: '🔮',
    color: '#4caf50',
    title: 'Table Comes Alive',
    subtitle: 'SubViewport · Map Editor · Peek v1 · Dice',
    timeline: 'Months 3–5',
    snippet: 'Map on the table, Peek into a 3D world, tokens move, physics dice roll.',
    goal: 'Re-implement the core VTT loop in Godot\'s rendering pipeline. The Peek mechanic gets its full Godot treatment with Vulkan rendering, SubViewport, and proper LOD. This is the research version\'s R2 but with better performance and visual fidelity.',
    tasks: [
      'SubViewport table surface — render world map scene from overhead orthographic camera',
      'Tile-based map editor for DM — drag terrain tiles, place props, save/load maps',
      'Fog of war system — shader-based masking, DM paints reveals, synced to all clients',
      'Peek mechanic v1 — Tween camera through table plane into world scene (Godot scene transition)',
      'Token system — MultiplayerSpawner for tokens, DM places all, players move their own',
      '3D physics dice with Jolt Physics — d4 through d20, networked roll results',
      'Full state sync via MultiplayerSynchronizer — map, tokens, fog, dice',
    ],
    deliverable: 'Functional VTT in Godot. DM builds a map, players Peek, tokens move, dice roll — all synced. Better visual quality than the research version.',
    gate: 'Is the Peek mechanic noticeably better in Godot vs the Three.js research version?',
  },
  {
    id: 'G2',
    track: 'GODOT',
    icon: '👥',
    color: '#2196f3',
    title: 'Avatar & Social Layer',
    subtitle: 'Character Creator · Emotes · Voice · Chat',
    timeline: 'Months 6–7',
    snippet: 'Expressive avatars, voice chat, the table feels like hanging out with friends.',
    goal: 'This is what separates Tavern Table from every browser VTT. Customizable 3D avatars sitting around the table, expressing reactions, talking to each other. Social immersion must be established before the game mechanics are layered on top.',
    tasks: [
      'Avatar creator — race, body, skin, hair, face, accessories with real-time preview',
      'Idle animation system — fidgeting, leaning, table-tapping, looking around',
      'Emote system — cheer, facepalm, thinking, laughing, scared (triggered by emote wheel)',
      'Emote wheel UI — radial menu on keybind, visible to all players',
      'WebRTC voice chat via GDExtension or Discord integration',
      'Text chat — in-character / OOC channels, whisper, party chat',
      'Persistent player profiles — avatar saved across campaigns',
    ],
    deliverable: 'Players look unique. Avatars react in real time. Voice and chat work. The table is socially alive even before any game content loads.',
    gate: 'Do players spend time personalizing their avatar? Do they use emotes unprompted?',
  },
  {
    id: 'G3',
    track: 'GODOT',
    icon: '⚔️',
    color: '#f44336',
    title: 'Character & Combat',
    subtitle: 'Full 5e · Initiative · Combat Loop',
    timeline: 'Months 8–10',
    snippet: 'Full 5e character sheets and a complete combat encounter from initiative to resolution.',
    goal: 'Players have complete 5e character sheets. Combat runs end-to-end without any paper. Every mechanic from the research version\'s R4 is reproduced here with Godot\'s UI framework — more polished, more integrated.',
    tasks: [
      'Full 5e character sheet — stats, skills, HP, class features, spell slots, death saves',
      'Character creation wizard — step-by-step (race, class, scores, background, equipment)',
      'Initiative tracker — auto-roll, drag-to-reorder, synced turn indicator',
      'Combat flow — action/bonus/reaction, grid movement with range display',
      'Encounter builder — SRD bestiary, drag enemies to init, CR vs party calculator',
      'Condition system — poisoned, stunned, prone, etc. — synced to all, shown on tokens',
      'Death saves UI — automated tracking with stabilization logic',
      'Combat log — scrollable timestamped history',
    ],
    deliverable: 'A real D&D group runs a complete combat encounter in Godot. Initiative to final blow — no paper, no alt-tab.',
    gate: 'Can a group of 4-5 players complete a combat session without hitting a blocking bug?',
  },
  {
    id: 'G4',
    track: 'GODOT',
    icon: '🧩',
    color: '#9c27b0',
    title: 'Puzzles & DM Power Tools',
    subtitle: 'Puzzle Engine · NPCs · Loot · Music · Rules',
    timeline: 'Months 11–13',
    snippet: 'Complete DM toolkit — puzzles, NPCs, loot, ambiance, and a rules reference.',
    goal: 'The DM can run any type of session — combat, exploration, social, puzzle — entirely within Tavern Table. No alt-tabbing to Notion, Spotify, or Discord.',
    tasks: [
      'Puzzle framework + quick templates (riddle, sliding tile, combo lock, Simon, word cipher)',
      'Multi-layer puzzle builder — chain puzzles, conditional hints, in-game triggers',
      'Puzzle viewport — renders on table, all players interact simultaneously',
      'NPC manager — portrait cards, quick dialogue display, relationship tracker',
      'Loot table system — weighted random generation, drag to player inventories',
      'Rules reference — searchable SRD database, bookmarks, homebrew entries',
      'DM notes — rich text, auto-save, tags, session log linking',
      'Music & ambiance controller — playlists, crossfade, SFX board (synced to players)',
    ],
    deliverable: 'DM runs a full non-combat session using only Tavern Table. Puzzles work. NPCs have dialogue. Music plays.',
    gate: 'Could a DM replace their entire current session toolkit (Notion + Spotify + Discord) with this app alone?',
  },
  {
    id: 'G5',
    track: 'GODOT',
    icon: '🌍',
    color: '#8bc34a',
    title: 'World Building & Peek 2.0',
    subtitle: 'Heightmap Terrain · 3D Props · Volumetric Fog',
    timeline: 'Months 14–16',
    snippet: 'The 3D world under the table becomes rich, beautiful, and a genuine wow moment.',
    goal: 'Peek 2.0 justifies the full Godot investment. Heightmap terrain, real 3D props, dynamic weather, and volumetric fog of war — the world beneath the table is something no browser-based VTT can match.',
    tasks: [
      'Heightmap terrain system — paint elevations, blend textures, define biomes',
      '3D prop library — trees, buildings, ruins, rivers, fences, bridges, dungeons',
      'Dynamic lighting — DM-controlled time-of-day and weather (rain, fog, snow) — day/night toggle first proven in Research R5 as a simple lerp between two lighting presets',
      'Peek 2.0 — smooth fly-through, point-of-interest focus, animated transition',
      'Volumetric fog of war — unexplored areas shrouded in VoxelGI-based mist',
      'Map import pipeline — images, Dungeondraft, Inkarnate exports as references',
      'Player Peek tools — personal pins, party-shared markers, distance measure',
    ],
    deliverable: 'Peeking is a "screenshot moment." Vulkan rendering makes the world look better than any existing VTT. Players share clips.',
    gate: 'Would a player spontaneously record and share a Peek clip without being asked?',
  },
  {
    id: 'G6',
    track: 'GODOT',
    icon: '🚀',
    color: '#ffc107',
    title: 'Polish, Platform & Launch',
    subtitle: 'Beta · Steam Early Access · Performance',
    timeline: 'Months 17–19',
    snippet: 'Production quality. Real groups choose it over Roll20. Ship to Early Access.',
    goal: 'Every system reaches production quality. A closed beta with real D&D groups proves the product is ready. Early Access launches on Steam and itch.io.',
    tasks: [
      'Multiple room environments: Basement, Tavern Backroom, Scholar\'s Study, Restaurant Booth — Tavern Backroom design first validated in Research R5',
      'DM environment customization — props, lighting, ambient audio per room',
      'UI/UX polish — transitions, tooltips, empty states, onboarding tutorial',
      'Performance optimization — LOD, occlusion culling, GPU profiling, network tick tuning',
      'Cloud save & sync via Supabase — campaign backup, cross-device access',
      'Accessibility — colorblind modes, scalable UI, full key remapping',
      'Closed beta with 10+ real D&D groups — structured feedback cycles',
      'Platform builds: Windows, macOS, Linux + web export evaluation',
      'Steam page, itch.io listing, trailer, press kit, marketing materials',
    ],
    deliverable: 'Early Access live. Beta groups choose Tavern Table for their actual campaigns.',
    gate: 'Do 70%+ of beta testers say they\'d use Tavern Table for their next campaign?',
  },
  {
    id: 'G7',
    track: 'GODOT',
    icon: '🌟',
    color: '#ff5722',
    title: 'Post-Launch & Expansion',
    subtitle: 'Mobile · Modding · Marketplace · VR · AI',
    timeline: 'Month 20+',
    snippet: 'Mobile companion, modding support, campaign marketplace, VR Peek, and AI DM tools.',
    goal: 'Grow Tavern Table into a community-driven D&D ecosystem. The best content — campaigns, maps, monsters, rooms — should come from the community, not just the dev team.',
    tasks: [
      'Mobile companion app — character sheet, dice, Peek for phones and tablets',
      'Modding API — custom environments, puzzle types, tokens, monster packs',
      'Campaign marketplace — community-created content with revenue share',
      'VR mode — physically lean over the table to Peek (Peek mechanic built for this)',
      'Additional rulesets — Pathfinder 2e, OSR systems, custom homebrew engines',
      'AI DM tools — NPC dialogue generation, encounter suggestions (Claude API integration)',
      'Spectator mode — watch live campaigns as a non-participant',
      'Session replay and streaming tools for content creators',
    ],
    deliverable: 'Active platform. Community creates content the dev team could not have built alone.',
    gate: 'Is the community generating campaigns, mods, and maps without being asked?',
  },
];

const ALT_PATHS = [
  {
    color: '#4caf50',
    badge: 'Path A',
    title: 'Minimal',
    timeline: '4–5 months to a testable website VTT',
    desc: 'Strip the research version to the bare loop: join via browser link → sit → see map → roll dice → run combat. No Peek, no avatars, no puzzles. Fastest validation path — no Tauri, no Supabase, just website + local server.',
    items: [
      '2D map on table surface only — no Peek mechanic',
      'Fixed placeholder avatars, combat-only session flow',
      'Single static room, share a URL link to join',
      'No Supabase, no Tauri — website only, local JSON persistence',
    ],
    tradeoff: 'No differentiator. If feedback is mediocre you won\'t know whether the concept or the scope is the problem.',
    rec: false,
  },
  {
    color: '#c9a227',
    badge: 'Path B',
    title: 'Balanced',
    timeline: '~7 months research website + ~19 months Godot',
    desc: 'Full research version as a website (R0–R7), Supabase at closed testing, Tauri desktop as optional R8. Then Godot production after the gate. Recommended — research informs production, minimal cloud dependency until needed.',
    items: [
      'Website-first: localhost dev → deployed URL → closed testing (no Tauri until R8)',
      'Supabase added only at R7 for invite-only auth and session persistence',
      'Tauri optional desktop download at R8 alongside the live website',
      'Proper feedback gate (70%+ threshold) before Godot commitment',
      'Peek mechanic validated in browser before production investment',
      'Steam Early Access as the public commercial product',
    ],
    tradeoff: 'Longer total timeline (~26 months end-to-end). Justified by dramatically lower risk on the Godot production investment, and by keeping cloud/desktop complexity out of the early dev phases.',
    rec: true,
  },
  {
    color: '#9c27b0',
    badge: 'Path C',
    title: 'Comprehensive',
    timeline: 'Research website + 18–24 months Godot',
    desc: 'Research version PLUS AI DM tools in v1 of production, web-first Godot export, and mobile companion at launch — built to displace Roll20 permanently.',
    items: [
      'Research website ships with Claude API AI DM tools',
      'Godot production: web export as primary target alongside desktop',
      'Mobile companion app at launch, not post-launch',
      'Foundry-style modding system from day one',
      'Discord Rich Presence + streaming/clip tools',
    ],
    tradeoff: 'Requires funding or 5+ person team. High scope risk. The version that could permanently end Roll20\'s dominance.',
    rec: false,
  },
];
